[package]
name = "weather"
version = "0.1.5"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cached-path = "0.6.0"
chrono = "0.4.23"
serde = { version = "1.0.151", features = ["derive"]}
serde-xml-rs = "0.6.0"
openssl = { version = "*", features = ["vendored"] }
