[package]
name = "weather"
version = "0.1.6"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cached-path = "0.6"
chrono = "0.4"
serde = { version = "1.0", features = ["derive"]}
serde-xml-rs = "0.6"

[target.'cfg(target_arch = "aarch64")'.dependencies]
openssl = { version = "*", features = ["vendored"] }

[target.'cfg(target_arch = "arm")'.dependencies]
openssl = { version = "*", features = ["vendored"] }
