name: Cross-Compile

on:
  push:
  workflow_dispatch:
  
jobs:
  cross-compile:
    #if: startsWith(github.ref, 'refs/tags/')
    name: cross compile
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: ['aarch64-linux-android', 'aarch64-unknown-linux-musl', 'arm-unknown-linux-musleabi', 'armv7-unknown-linux-gnueabihf']
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.83.0
        default: true
    - run: cargo install cross --git https://github.com/cross-rs/cross
    - run: cross build --release --target ${{matrix.target}}
    - run: mv target/${{matrix.target}}/release/israel-weather-rs target/${{matrix.target}}/release/israel-weather-rs_${{matrix.target}}
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: target/${{matrix.target}}/release/israel-weather-rs_${{matrix.target}}
    - uses: actions/upload-artifact@v3
      with:
        name: israel-weather-rs_${{matrix.target}}
        path: target/${{matrix.target}}/release/israel-weather-rs_${{matrix.target}}
