name: Cross-Compile Release

on:
  workflow_dispatch:
  release:
    types: [created]
  
jobs:
  aarch64-linux-android:
    name: cross compile for aarch64-linux-android
    runs-on: ubuntu-latest
    container: ghcr.io/cross-rs/aarch64-linux-android
# 'aarch64-unknown-linux-musl', 'arm-unknown-linux-musleabi', 'armv7-unknown-linux-gnueabihf', 'x86_64-pc-windows-gnu', 'x86_64-unknown-linux-musl']
    steps:
    - uses: actions/checkout@v3
    - run: cross build --release --target aarch64-linux-android
    - uses: actions/upload-artifact@v3
      with:
        name: aarch64-linux-android_weather
        path: target/aarch64-linux-android/release/weather
