name: Cross-Compile

on:
  push:
  
jobs:
  cross-compile:
    if: startsWith(github.ref, 'refs/tags/')
    name: cross compile
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: ['aarch64-linux-android', 'aarch64-unknown-linux-musl', 'arm-unknown-linux-musleabi', 'armv7-unknown-linux-gnueabihf']
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.67.0
        override: true
    - run: curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
    - run: cargo binstall cross --no-confirm --version 0.2.5
    - run: cross build --release --target ${{matrix.target}}
    - run: mv target/${{matrix.target}}/release/weather target/${{matrix.target}}/release/weather_${{matrix.target}}
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: target/${{matrix.target}}/release/weather_${{matrix.target}}
    - uses: actions/upload-artifact@v3
      with:
        name: weather_${{matrix.target}}
        path: target/${{matrix.target}}/release/weather_${{matrix.target}}
