name: Cross-Compile Release

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  release:
    name: Release - ${{ matrix.platform.release_for }}
    strategy:
      matrix:
        platform:
          - release_for: Android
            os: ubuntu-20.04
            target: aarch64-linux-android
            bin: weather
            name: weather_aarch64-linux-android.tar.gz
            command: build

          - release_for: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: weather.exe
            name: weather-Windows-x86_64.zip
            command: both

          - release_for: macOS-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin
            bin: weather
            name: weather-Darwin-x86_64.tar.gz
            command: both

          - release_for: Linux
            os: ubuntu-20.04
            target: x86_64-unknown-linux-musl
            bin: weather
            name: weather_x86_64-unknown-linux-musl.tar.gz
            command: build
         
    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: ${{ matrix.platform.command }}
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true
