name: Cross-Compile

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  
jobs:
  cross-compile:
    name: cross compile
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: ['aarch64-linux-android', 'aarch64-unknown-linux-musl', 'arm-unknown-linux-musleabi', 'armv7-unknown-linux-gnueabihf']
    steps:
    - uses: actions/checkout@v3
    - run: curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
    - run: cargo binstall cross --no-confirm
    - run: cross build --release --target ${{matrix.target}}
    - name: Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: target/${{matrix.target}}/release/weather
    - uses: actions/upload-artifact@v3
      with:
        name: ${{matrix.target}}_weather
        path: target/${{matrix.target}}/release/weather
