name: E2E test every 6 hours

on:
  schedule:
    - cron: "1 6/6 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Get latest release asset
        run: curl -s "https://api.github.com/repos/barakplasma/israel-weather-rs/releases/latest" | jq -r '.assets[] | select(.browser_download_url | contains("ubuntu")) | .browser_download_url' | xargs curl -LO

      - name: Make executable
        run: chmod +x ./israel-weather-rs_ubuntu-latest

      - name: Alert me for rain
        # template https://repeatit.io/#/share/eyJ0ZW1wbGF0ZSI6Int7cmFuZ2UgLn19IyBBcyBvZiB7ey5Gb3JlY2FzdFRpbWV9fSNcbnt7aWYgZ3QgLlJhaW4gMC4wfX17ey5SYWlufX0gbW0gb2YgUmFpbiBhcmUgZXhwZWN0ZWR7e2VuZH19XG5Db25kaXRpb25zIGV4cGVjdGVkIGFyZToge3suV2VhdGhlckNvZGVFbmdsaXNofX1cblRlbXBlcmF0dXJlOiB7ey5NaW5UZW1wfX1jIC0ge3suTWF4VGVtcH19Y1xue3tlbmR9fSIsImlucHV0IjoiWyAge1xuICAgIFwiRm9yZWNhc3RUaW1lXCI6IFwiMjAyNS0wMi0yNFQwMjowMDowMCswMDowMFwiLFxuICAgIFwiVGVtcGVyYXR1cmVcIjogNi4wLFxuICAgIFwiUmVsYXRpdmVIdW1pZGl0eVwiOiA2My4wLFxuICAgIFwiV2luZFNwZWVkXCI6IDUuMCxcbiAgICBcIlJhaW5cIjogMC4wLFxuICAgIFwiV2luZERpcmVjdGlvblwiOiA5MC4wLFxuICAgIFwiRGV3UG9pbnRUZW1wXCI6IC0xLjAsXG4gICAgXCJIZWF0U3RyZXNzXCI6IDQuNixcbiAgICBcIkhlYXRTdHJlc3NMZXZlbFwiOiAwLjAsXG4gICAgXCJGZWVsc0xpa2VcIjogNS4wLFxuICAgIFwiV2luZENoaWxsXCI6IDUuMCxcbiAgICBcIldlYXRoZXJDb2RlXCI6IDE1NDAsXG4gICAgXCJXZWF0aGVyQ29kZUVuZ2xpc2hcIjogXCJDbG91ZHksIHBvc3NpYmxlIHJhaW5cIixcbiAgICBcIk1pblRlbXBcIjogNi4wLFxuICAgIFwiTWF4VGVtcFwiOiA3LjAsXG4gICAgXCJVdkluZGV4XCI6IG51bGwsXG4gICAgXCJVdkluZGV4TWF4XCI6IG51bGxcbiAgfVxuXSIsImNvbmZpZyI6eyJ0ZW1wbGF0ZSI6InRleHQiLCJmdWxsU2NyZWVuSFRNTCI6ZmFsc2UsImZ1bmN0aW9ucyI6IiIsIm9wdGlvbnMiOlsibGl2ZSJdLCJpbnB1dFR5cGUiOiJ5YW1sIn19
        run: ./israel-weather-rs_ubuntu-latest | tee weather.json | curl --globoff -H p:$(jq "if .Rain > 0.02 then 4 else 1 end" weather.json) -H Actions:"view, Open IMS, https://ims.gov.il/en/cityPortal?lid=84" -d @- 'ntfy.sh/${{ secrets.NTFY_TOPIC }}?tpl=yes&t=%7B%7Brange%20.%7D%7D%23%20As%20of%20%7B%7B.ForecastTime%7D%7D%23%0A%7B%7Bif%20gt%20.Rain%200.0%7D%7D%7B%7B.Rain%7D%7D%20mm%20of%20Rain%20are%20expected%7B%7Bend%7D%7D%0AConditions%20expected%20are%3A%20%7B%7B.WeatherCodeEnglish%7D%7D%0ATemperature%3A%20%7B%7B.MinTemp%7D%7Dc%20-%20%7B%7B.MaxTemp%7D%7Dc%0A%7B%7Bend%7D%7D'

      - name: Run E2E test - All
        run: ./israel-weather-rs_ubuntu-latest --all

      - name: Run E2E test - Offline
        run: ./israel-weather-rs_ubuntu-latest --offline
