name: E2E test every 6 hours

on:
  schedule:
    - cron: "1 6/6 * * *"
  workflow_dispatch:
  push:
    branches: [ "teest" ]

env:
  template: |
    |time|desc|temp|
    |---|---|---|
    {{range .}}|{{slice .ForecastTime 11 16}}|{{if gt .Rain 0.0}}{{.Rain}} mm of Rain are expected. {{.WeatherCodeEnglish}}{{else}}No rain expected. {{.WeatherCodeEnglish}}{{end}}|{{.MinTemp}}c-{{.MaxTemp}}c|
    {{end}}
  # https://repeatit.io/#/share/eyJ0ZW1wbGF0ZSI6Inx0aW1lfGRlc2N8dGVtcHxcbnwtLS18LS0tfC0tLXxcbnt7cmFuZ2UgLn19fHt7c2xpY2UgLkZvcmVjYXN0VGltZSAxMSAxNn19fHt7aWYgZ3QgLlJhaW4gMC4wfX17ey5SYWlufX0gbW0gb2YgUmFpbiBhcmUgZXhwZWN0ZWQuIHt7LldlYXRoZXJDb2RlRW5nbGlzaH19e3tlbHNlfX1ObyByYWluIGV4cGVjdGVkLiB7ey5XZWF0aGVyQ29kZUVuZ2xpc2h9fXt7ZW5kfX18e3suTWluVGVtcH19Yy17ey5NYXhUZW1wfX1jfFxue3tlbmR9fSIsImlucHV0IjoiWyAge1xuICAgIFwiRm9yZWNhc3RUaW1lXCI6IFwiMjAyNS0wMi0yNFQwMjowMDowMCswMDowMFwiLFxuICAgIFwiVGVtcGVyYXR1cmVcIjogNi4wLFxuICAgIFwiUmVsYXRpdmVIdW1pZGl0eVwiOiA2My4wLFxuICAgIFwiV2luZFNwZWVkXCI6IDUuMCxcbiAgICBcIlJhaW5cIjogMC4wLFxuICAgIFwiV2luZERpcmVjdGlvblwiOiA5MC4wLFxuICAgIFwiRGV3UG9pbnRUZW1wXCI6IC0xLjAsXG4gICAgXCJIZWF0U3RyZXNzXCI6IDQuNixcbiAgICBcIkhlYXRTdHJlc3NMZXZlbFwiOiAwLjAsXG4gICAgXCJGZWVsc0xpa2VcIjogNS4wLFxuICAgIFwiV2luZENoaWxsXCI6IDUuMCxcbiAgICBcIldlYXRoZXJDb2RlXCI6IDE1NDAsXG4gICAgXCJXZWF0aGVyQ29kZUVuZ2xpc2hcIjogXCJDbG91ZHksIHBvc3NpYmxlIHJhaW5cIixcbiAgICBcIk1pblRlbXBcIjogNi4wLFxuICAgIFwiTWF4VGVtcFwiOiA3LjAsXG4gICAgXCJVdkluZGV4XCI6IG51bGwsXG4gICAgXCJVdkluZGV4TWF4XCI6IG51bGxcbiAgfSwge1xuICAgIFwiRm9yZWNhc3RUaW1lXCI6IFwiMjAyNS0wMi0yNFQwODowMDowMCswMDowMFwiLFxuICAgIFwiVGVtcGVyYXR1cmVcIjogNi4wLFxuICAgIFwiUmVsYXRpdmVIdW1pZGl0eVwiOiA2My4wLFxuICAgIFwiV2luZFNwZWVkXCI6IDUuMCxcbiAgICBcIlJhaW5cIjogMC4wLFxuICAgIFwiV2luZERpcmVjdGlvblwiOiA5MC4wLFxuICAgIFwiRGV3UG9pbnRUZW1wXCI6IC0xLjAsXG4gICAgXCJIZWF0U3RyZXNzXCI6IDQuNixcbiAgICBcIkhlYXRTdHJlc3NMZXZlbFwiOiAwLjAsXG4gICAgXCJGZWVsc0xpa2VcIjogNS4wLFxuICAgIFwiV2luZENoaWxsXCI6IDUuMCxcbiAgICBcIldlYXRoZXJDb2RlXCI6IDE1NDAsXG4gICAgXCJXZWF0aGVyQ29kZUVuZ2xpc2hcIjogXCJDbG91ZHksIHBvc3NpYmxlIHJhaW5cIixcbiAgICBcIk1pblRlbXBcIjogNi4wLFxuICAgIFwiTWF4VGVtcFwiOiA3LjAsXG4gICAgXCJVdkluZGV4XCI6IG51bGwsXG4gICAgXCJVdkluZGV4TWF4XCI6IG51bGxcbiAgfVxuXSIsImNvbmZpZyI6eyJ0ZW1wbGF0ZSI6InRleHQiLCJmdWxsU2NyZWVuSFRNTCI6ZmFsc2UsImZ1bmN0aW9ucyI6IiIsIm9wdGlvbnMiOlsibGl2ZSJdLCJpbnB1dFR5cGUiOiJ5YW1sIn19

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Get latest release asset
        # jq command https://play.jqlang.org/s/s0plyKVNy1fs_Wv
        run: curl -s "https://api.github.com/repos/barakplasma/israel-weather-rs/releases/latest" | jq -r '.assets[] | select(.browser_download_url | contains("ubuntu")) | .browser_download_url' | xargs curl -LO

      - name: Make executable
        run: chmod +x ./israel-weather-rs_ubuntu-latest

      - name: Alert me for rain
        run: |
          ./israel-weather-rs_ubuntu-latest -n 24 | tee weather.json | curl --globoff \
          -H X-Priority:$(jq "if max_by(.Rain).Rain > 0 then 4 else 1 end" weather.json) \
          -H X-Tags:$(jq 'map(if .Rain > 0 then "cloud_with_rain" else "sun_behind_small_cloud" end)' weather.json) \
          -H X-Actions:"view, Open Action, https://github.com/barakplasma/israel-weather-rs/actions/workflows/e2e_test.yml" \
          -H X-Click:"https://ims.gov.il/en/cityPortal?lid=84" \
          -H X-Template:yes \
          -d @- \
          --data-urlencode message=${{ env.template }} \
          ntfy.sh/${{ secrets.NTFY_TOPIC }}

      - name: Run E2E test - Offline
        run: ./israel-weather-rs_ubuntu-latest --offline -n 24
