name: E2E test every 6 hours

on:
  schedule:
    - cron: "1 6/6 * * *"
  workflow_dispatch:
  push:
    branches: [ "teest" ]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get latest release asset
        # jq command https://play.jqlang.org/s/s0plyKVNy1fs_Wv
        run: curl -s "https://api.github.com/repos/barakplasma/israel-weather-rs/releases/latest" | jq -r '.assets[] | select(.browser_download_url | contains("ubuntu")) | .browser_download_url' | xargs curl -LO

      - name: Make executable
        run: chmod +x ./israel-weather-rs_ubuntu-latest

      - name: Get Weather
        run: ./israel-weather-rs_ubuntu-latest -n 24 | tee weather.json

      - uses: actions/upload-artifact@v4
        with:
          name: weather.json
          path: weather.json
          retention-days: 14

      - name: Send notification
        run: |
          curl ntfy.sh/${{ secrets.NTFY_TOPIC }} --globoff \
          -H X-Priority:$(jq "if max_by(.Rain).Rain > 0 then 4 else 1 end" weather.json) \
          -H X-Tags:$(jq 'map(if .Rain > 0 then "cloud_with_rain" else "sun_behind_small_cloud" end)' weather.json) \
          -H X-Actions:"view, Open Action, https://github.com/barakplasma/israel-weather-rs/actions/workflows/e2e_test.yml" \
          -H X-Click:"https://ims.gov.il/en/cityPortal?lid=84" \
          -H X-Template:"yes" \
          -H X-Title:"Weather-Alert" \
          -H Content-Type:"application/json" \
          --data @weather.json \
          --data-urlencode message@ntfy-template.tmpl
