name: E2E test every 6 hours

on:
  schedule:
  - cron: "0 6/6 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - run: curl -s https://api.github.com/repos/barakplasma/israel-weather-rs/releases/latest | grep "browser_download_url.*ubuntu" | cut -d ":" -f 2,3 | tr -d \" | wget -qi -
    - run: chmod +x ./weather_ubuntu-latest
    - run: ./weather_ubuntu-latest
