name: E2E test every 6 hours

on:
  schedule:
    - cron: "1 6/6 * * *"
  workflow_dispatch:
  push:
    branches: [ "teest" ]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get latest release asset
        # jq command https://play.jqlang.org/s/s0plyKVNy1fs_Wv
        run: curl -s "https://api.github.com/repos/barakplasma/israel-weather-rs/releases/latest" | jq -r '.assets[] | select(.browser_download_url | contains("ubuntu")) | .browser_download_url' | xargs curl -LO

      - name: Make executable
        run: chmod +x ./israel-weather-rs_ubuntu-latest

      - name: Cache tmp dir
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-cache-${{ hashFiles('**/src/lib.rs') }}
          path: /tmp
          save-always: yes

      - name: Get Weather
        run: ./israel-weather-rs_ubuntu-latest -n 24 | tee weather.json

      - uses: actions/upload-artifact@v4
        with:
          name: weather.json
          path: weather.json
          retention-days: 14

      - name: Send notification
        run: curl --data @weather.json ntfy.sh/${{ secrets.NTFY_TOPIC }}?tpl=yes&m=$(cat ntfy-template.tmpl | jq -sRr @uri)
