name: E2E test every 6 hours

on:
  schedule:
  - cron: "1 6/6 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - run: curl -s "https://api.github.com/repos/barakplasma/israel-weather-rs/releases/latest" | jq -r '.assets[] | select(.browser_download_url | contains("ubuntu")) | .browser_download_url' | xargs curl -LO
    - run: chmod +x ./weather_ubuntu-latest
    - run: ./weather_ubuntu-latest
