name: E2E test every 6 hours

on:
  schedule:
  - cron: "1 6/6 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - run: gh api repos/barakplasma/israel-weather-rs/releases/latest | jq -r '.assets[] | select(.name | contains("ubuntu")) | .id | first' | gh release asset download --repo barakplasma/israel-weather-rs $(cat) --clobber
    - run: chmod +x ./weather_ubuntu-latest
    - run: ./weather_ubuntu-latest
