name: E2E test every 6 hours

on:
  schedule:
    - cron: "1 6/6 * * *"
  workflow_dispatch:


jobs:
  end-to-end-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install jq curl

      - name: Get latest release asset
        # jq command https://play.jqlang.org/s/s0plyKVNy1fs_Wv
        run: curl -s "https://api.github.com/repos/barakplasma/israel-weather-rs/releases/latest" | jq -r '.assets[] | select(.browser_download_url | contains("ubuntu")) | .browser_download_url' | xargs curl -LO

      - name: Make executable
        run: chmod +x ./israel-weather-rs_ubuntu-latest

      - name: Get Weather
        run: ./israel-weather-rs_ubuntu-latest -n 24 | tee weather.json

      - uses: actions/upload-artifact@v4
        with:
          name: weather.json
          path: weather.json
          retention-days: 14
      
      - name: Will it rain?
        run: echo "RAIN=$(jq "max_by(.Rain).Rain > 0" weather.json)" >> $GITHUB_ENV

      - name: Send notification
        run: |
          curl -H Priority:$([ "$RAIN" == "true" ] && echo 4 || echo 1) \
          -H Click:"https://ims.gov.il/en/cityPortal?lid=84" \
          --url-query "title=$(if [ "$RAIN" == "true" ]; then echo "Rain Expected"; else echo "No Rain"; fi)" \
          --url-query message@ntfy-template.tmpl \
          -H Content-Type:"application/json" \
          -H Template:yes \
          --data @weather.json \
          'ntfy.sh/${{ secrets.NTFY_TOPIC }}'