name: E2E test every 6 hours

on:
  schedule:
  - cron: "0 6/6 * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - runs: curl -s https://api.github.com/repos/barakplasma/israel-weather-rs/releases/latest | grep "browser_download_url.*ubuntu" | cut -d : -f 2,3 | tr -d \" | wget -qi -
    - runs: ./weather_ubuntu-latest
