name: E2E test every 6 hours

on:
  schedule:
    - cron: "1 6/6 * * *"
  workflow_dispatch:

env:
  template: "{{range .}}{{slice .ForecastTime 11 16}}{{if gt .Rain 0.0}}{{.Rain}} mm of Rain are expected. {{.WeatherCodeEnglish}}{{else}}No rain expected. {{.WeatherCodeEnglish}}{{end}}. {{.MinTemp}}c-{{.MaxTemp}}c{{end}}"


# https://repeatit.io/#/share/eyJ0ZW1wbGF0ZSI6Int7cmFuZ2UgLn19XG4jIHt7c2xpY2UgLkZvcmVjYXN0VGltZSAxMSAxNn19XG57e2lmIGd0IC5SYWluIDAuMH19e3suUmFpbn19IG1tIG9mIFJhaW4gYXJlIGV4cGVjdGVkLiB7ey5XZWF0aGVyQ29kZUVuZ2xpc2h9fXt7ZWxzZX19Tm8gcmFpbiBleHBlY3RlZC4ge3suV2VhdGhlckNvZGVFbmdsaXNofX17e2VuZH19LiB7ey5NaW5UZW1wfX1jLXt7Lk1heFRlbXB9fWNcbnt7ZW5kfX0iLCJpbnB1dCI6IlsgIHtcbiAgICBcIkZvcmVjYXN0VGltZVwiOiBcIjIwMjUtMDItMjRUMDI6MDA6MDArMDA6MDBcIixcbiAgICBcIlRlbXBlcmF0dXJlXCI6IDYuMCxcbiAgICBcIlJlbGF0aXZlSHVtaWRpdHlcIjogNjMuMCxcbiAgICBcIldpbmRTcGVlZFwiOiA1LjAsXG4gICAgXCJSYWluXCI6IDAuMCxcbiAgICBcIldpbmREaXJlY3Rpb25cIjogOTAuMCxcbiAgICBcIkRld1BvaW50VGVtcFwiOiAtMS4wLFxuICAgIFwiSGVhdFN0cmVzc1wiOiA0LjYsXG4gICAgXCJIZWF0U3RyZXNzTGV2ZWxcIjogMC4wLFxuICAgIFwiRmVlbHNMaWtlXCI6IDUuMCxcbiAgICBcIldpbmRDaGlsbFwiOiA1LjAsXG4gICAgXCJXZWF0aGVyQ29kZVwiOiAxNTQwLFxuICAgIFwiV2VhdGhlckNvZGVFbmdsaXNoXCI6IFwiQ2xvdWR5LCBwb3NzaWJsZSByYWluXCIsXG4gICAgXCJNaW5UZW1wXCI6IDYuMCxcbiAgICBcIk1heFRlbXBcIjogNy4wLFxuICAgIFwiVXZJbmRleFwiOiBudWxsLFxuICAgIFwiVXZJbmRleE1heFwiOiBudWxsXG4gIH0sIHtcbiAgICBcIkZvcmVjYXN0VGltZVwiOiBcIjIwMjUtMDItMjRUMDg6MDA6MDArMDA6MDBcIixcbiAgICBcIlRlbXBlcmF0dXJlXCI6IDYuMCxcbiAgICBcIlJlbGF0aXZlSHVtaWRpdHlcIjogNjMuMCxcbiAgICBcIldpbmRTcGVlZFwiOiA1LjAsXG4gICAgXCJSYWluXCI6IDAuMCxcbiAgICBcIldpbmREaXJlY3Rpb25cIjogOTAuMCxcbiAgICBcIkRld1BvaW50VGVtcFwiOiAtMS4wLFxuICAgIFwiSGVhdFN0cmVzc1wiOiA0LjYsXG4gICAgXCJIZWF0U3RyZXNzTGV2ZWxcIjogMC4wLFxuICAgIFwiRmVlbHNMaWtlXCI6IDUuMCxcbiAgICBcIldpbmRDaGlsbFwiOiA1LjAsXG4gICAgXCJXZWF0aGVyQ29kZVwiOiAxNTQwLFxuICAgIFwiV2VhdGhlckNvZGVFbmdsaXNoXCI6IFwiQ2xvdWR5LCBwb3NzaWJsZSByYWluXCIsXG4gICAgXCJNaW5UZW1wXCI6IDYuMCxcbiAgICBcIk1heFRlbXBcIjogNy4wLFxuICAgIFwiVXZJbmRleFwiOiBudWxsLFxuICAgIFwiVXZJbmRleE1heFwiOiBudWxsXG4gIH1cbl0iLCJjb25maWciOnsidGVtcGxhdGUiOiJ0ZXh0IiwiZnVsbFNjcmVlbkhUTUwiOmZhbHNlLCJmdW5jdGlvbnMiOiIiLCJvcHRpb25zIjpbImxpdmUiXSwiaW5wdXRUeXBlIjoieWFtbCJ9fQ==

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Get latest release asset
        # jq command https://play.jqlang.org/s/s0plyKVNy1fs_Wv
        run: curl -s "https://api.github.com/repos/barakplasma/israel-weather-rs/releases/latest" | jq -r '.assets[] | select(.browser_download_url | contains("ubuntu")) | .browser_download_url' | xargs curl -LO

      - name: Make executable
        run: chmod +x ./israel-weather-rs_ubuntu-latest

      - name: Alert me for rain
        # jq command https://play.jqlang.org/s/k9O1YEC-3hMC-Xc
        run: ./israel-weather-rs_ubuntu-latest -n 24 | tee weather.json | curl --globoff -H p:$(jq "if .[0].Rain > 0 then 4 else 1 end" weather.json) -H tag:$(jq "if .[0].Rain > 0 then \"cloud_with_rain\" else \"sun_behind_small_cloud\" end" weather.json) -H Actions:"view, Open IMS, https://ims.gov.il/en/cityPortal?lid=84; view, Open Action, https://github.com/barakplasma/israel-weather-rs/actions/workflows/e2e_test.yml" --data-urlencode 't={{ env.template }}' --data-urlencode 'template=yes' -d @- 'ntfy.sh/${{ secrets.NTFY_TOPIC }}'

      - name: Run E2E test - Offline
        run: ./israel-weather-rs_ubuntu-latest --offline
