name: E2E test every 6 hours

on:
  schedule:
    - cron: "1 6/6 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Get latest release asset
        run: curl -s "https://api.github.com/repos/barakplasma/israel-weather-rs/releases/latest" | jq -r '.assets[] | select(.browser_download_url | contains("ubuntu")) | .browser_download_url' | xargs curl -LO

      - name: Make executable
        run: chmod +x ./israel-weather-rs_ubuntu-latest

      - name: Run E2E test - Tel Aviv
        run: ./israel-weather-rs_ubuntu-latest

      - name: Run E2E test - All
        run: ./israel-weather-rs_ubuntu-latest --all

      - name: Run E2E test - Offline
        run: ./israel-weather-rs_ubuntu-latest --offline

      - name: Alert me for rain
        run: ./israel-weather-rs_ubuntu-latest | tail -n 21 | curl --globoff -H "Priority: low" -d @- '${{ secrets.NTFY_URL }}'
