name: E2E test every 6 hours

on:
  schedule:
    - cron: "1 6/6 * * *"
  workflow_dispatch:
  push:
    branches: [ "teest" ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get latest release asset
        # jq command https://play.jqlang.org/s/s0plyKVNy1fs_Wv
        run: curl -s "https://api.github.com/repos/barakplasma/israel-weather-rs/releases/latest" | jq -r '.assets[] | select(.browser_download_url | contains("ubuntu")) | .browser_download_url' | xargs curl -LO

      - name: Make executable
        run: chmod +x ./israel-weather-rs_ubuntu-latest

      - name: Get Weather
        run: ./israel-weather-rs_ubuntu-latest -n 24 | tee weather.json

      - uses: actions/upload-artifact@v4
        with:
          name: weather.json
          path: weather.json
          retention-days: 14
      
      - name: Will it rain?
        run: export RAIN=$(jq "max_by(.Rain).Rain > 0" weather.json); echo $RAIN

      - name: Send notification
        run: curl -H Priority:4 -H Click:"https://ims.gov.il/en/cityPortal?lid=84" --data @weather.json 'ntfy.sh/${{ secrets.NTFY_TOPIC }}' --data-urlencode m@ntfy-template.tmpl
