name: Periodic Test of IMS data

on:
  schedule:
  - cron: "0 6/6 * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
    - run: cargo run
