name: Release - Desktop OS

on:
  release:
    types: [created]

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@master
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --release --target-dir binaries
      - run: mv binaries/weather binaries/weather_${{matrix.os}}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: binaries/weather_${{matrix.os}}
