name: Release - Desktop OS

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  release:
    name: release ${{ matrix.os }}
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - run: npm install -g shx
      - name: Build
        run: cargo build --release
      - name: Check semver
        uses: obi1kenobi/cargo-semver-checks-action@v2
      - run: shx cp ./target/release/weather ./target/release/weather_${{matrix.os}}
        if: runner.os == 'Linux' || runner.os == 'macOS'
      - run: shx cp target/release/weather.exe target/release/weather_windows-latest.exe
        if: runner.os == 'Windows'
      - name: Release Linux
        if: runner.os == 'Linux' || runner.os == 'macOS'
        uses: softprops/action-gh-release@v1
        with:
          files: ./target/release/weather_${{matrix.os}}
      - name: Release Windows
        if: runner.os == 'Windows'
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/weather_windows-latest.exe
