name: Release - Desktop OS

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  release-unix:
    name: release ${{ matrix.os }}
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Build
        run: cargo build --release
      - run: cp ./target/release/israel-weather-rs ./target/release/israel-weather-rs_${{matrix.os}}
      - name: Release Linux
        uses: softprops/action-gh-release@v1
        with:
          files: ./target/release/israel-weather-rs_${{matrix.os}}
  release-windows:
    name: release windows-latest
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: npm install -g shx
      - name: Build
        run: cargo build --release
      - run: shx cp target/release/israel-weather-rs.exe target/release/israel-weather-rs_windows-latest.exe
      - name: Release Windows
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/israel-weather-rs_windows-latest.exe

