name: Test

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '.github/**'
      - '.vscode/**'

  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - '.github/**'
      - '.vscode/**'

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
    - run: cargo test
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
    - run: cargo run
